theme: jekyll-theme-cayman
title: APA
description: C++ big integers and dynamic precision floating points.
github_username: mrdcvlsc
github_repo: "APA"

use_math: true
show_description: true
show_image: false
show_tags: true

markdown: kramdown
kramdown:
  math_engine: katex