name: clang

on:
  push:
    branches: [ version_4, version_4.4, main ]
  pull_request:
    branches: [ version_4, version_4.4, main ]

jobs:
  header-mode-tests:

    runs-on: ubuntu-latest
    
    steps:

    - name: install clang
      run: sudo apt install clang

    - uses: actions/checkout@v2

    - name: compile and run tests in header mode
      run: make -j all_test CC=clang++