name: mingw64

on:
  push:
    branches: [ version_4, version_4.4, main ]
  pull_request:
    branches: [ version_4, version_4.4, main ]

jobs:
  mingw64-windows-tests-base2_16:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile and run tests in header mode base 2^16
      run: mingw32-make test BASE2_RAISED_BY=16

  mingw64-windows-tests-base2_32:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile and run tests in header mode base 2^32
      run: mingw32-make test BASE2_RAISED_BY=32

  mingw64-windows-tests-base2_64:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile and run tests in header mode base 2^64
      run: mingw32-make test BASE2_RAISED_BY=64